# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'entryUser.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import face_detetct as fd


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(672, 418)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(170, 60, 361, 271))
        self.label.setText("")
        self.label.setObjectName("label")
        self.retranslateUi(Dialog)
        self.myfacedetect = fd.detect('')
        self.label.setStyleSheet("background-color: black")

        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))

    # 录入人脸信息的函数  self.label变量是用来显示图像的标签对象, window.id变量是当前正在录入人脸信息的用户id
    def capture(self):
        self.myfacedetect.set_name(name = '邮箱号') #此处需填写录入人脸的邮箱号
        pass

